# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='extension',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
